import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import { Leva } from "leva";
import LevaWrapper from "./components/LevaWrapper";
import Footer from "./sections/Footer";



const inter = localFont({
  src: [
    { path: "../public/fonts/InterDisplay-Regular.woff2", weight: "400", style: "normal" }, 
    { path: "../public/fonts/InterDisplay-Medium.woff2", weight: "500", style: "normal" },
    { path: "../public/fonts/InterDisplay-SemiBold.woff2", weight: "600", style: "normal" },
    { path: "../public/fonts/InterDisplay-Bold.woff2", weight: "700", style: "normal" }
  ],
  variable: "--font-inter-display"
});

export const metadata: Metadata = {
  title: "tradoo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        <Header />
        {children}
        <LevaWrapper />
        <Footer/>
      </body>
    </html>
  );
}
